resources:
  repositories:
  - repository: javacode # The name used to reference this repository in the checkout step
    type: github
    endpoint: arshadmech
    name: arshadmech/javacode
trigger:
- master

pool:
  vmImage: ubuntu-latest
steps: 
- checkout: javacode

stages:
 - stage: Build
   jobs:
    - job: Build
      steps:
       - task: Maven@4
         inputs:
          mavenPomFile: 'pom.xml'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false
       - task: CopyFiles@2
         inputs:
           SourceFolder: '$(system.defaultworkingdirectory)'
           Contents: '**/*.war'
           TargetFolder: '$(build.artifactstagingdirectory)'
       - task: PublishBuildArtifacts@1
         inputs:
           PathtoPublish: '$(Build.ArtifactStagingDirectory)'
           ArtifactName: 'drop'
           
 - stage: Deploy
   jobs:
    - job: Deploy
      pool: 
       vmImage: ubuntu-latest
      steps: 
       - task: S3Upload@1
         inputs:
           awsCredentials: 'ovaledge s3'
           regionName: 'ap-south-1'
           bucketName: 'qa-weekly-backups'
           sourceFolder: '$(System.DefaultWorkingDirectory)/_oval edge-Maven-CI (1)/drop/webapp/target'
           globExpressions: '*.war'
