resources:
  repositories:
  - repository: javacode # The name used to reference this repository in the checkout step
    type: github
    endpoint: arshadmech
    name: arshadmech/javacode
trigger:
- master

pool:
  vmImage: ubuntu-latest
steps: 
- checkout: javacode

stages:
 - stage: Build
   jobs:
    - job: Build
      steps:
       - task: Maven@4
         inputs:
          mavenPomFile: '/home/vsts/work/1/s/javacode/pom.xml'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false
       - task: CopyFiles@2
         inputs:
           SourceFolder: '/home/vsts/work/1/s/javacode/webapp/target/'
           Contents: '*.war'
           TargetFolder: '/home/vsts/work/1/a/javacode/webapp/target'
       - task: PublishBuildArtifacts@1
         inputs:
           PathtoPublish: '(build.artifactstagingdirectory)/javacode/webapp/target'
           ArtifactName: 'drop'
           
 - stage: Deploy
   jobs:
    - job: Deploy
      pool: 
       vmImage: ubuntu-latest
      steps: 
       - task: S3Upload@1
         inputs:
           awsCredentials: 'ovaledge s3'
           regionName: 'ap-south-1'
           bucketName: 'qa-weekly-backups'
           sourceFolder: '$(build.artifactstagingdirectory)/javacode/webapp/target'
           globExpressions: '*.war'
